CC = gcc
CXX = g++
AR = ar
ENABLE_GPIOD ?= 1
INSTALL ?= install
PREFIX ?= /usr/local
BINDIR ?= $(PREFIX)/bin
OPENHSPDIR ?= $(PREFIX)/lib/openhsp
APPDIR ?= $(PREFIX)/share/applications
PIXMAPDIR ?= $(PREFIX)/share/pixmaps

CFLAGS_ENV = # 32bit
CFLAGS_DISH = -Wno-write-strings --exec-charset=UTF-8 -DHSPDISH -DHSPLINUX -DHSPDEBUG -DUSE_OBAQ -DHSP_COM_UNSUPPORTED $(CFLAGS_ENV)
CFLAGS_GP = -Wno-write-strings --exec-charset=UTF-8 -DHSPDISH -DHSPDISHGP -DHSPLINUX -DHSPDEBUG -DHSP_COM_UNSUPPORTED -DPNG_ARM_NEON_OPT=0 -I src/hsp3dish/extlib/src -I src/hsp3dish/extlib/src/glew -I src/hsp3dish/gameplay/src -std=c++11 $(CFLAGS_ENV)
CFLAGS_CL = -Wno-write-strings -std=c++11 --exec-charset=UTF-8 -DHSPLINUX -DHSPDEBUG -DHSP_COM_UNSUPPORTED $(CFLAGS_ENV)
CFLAGS_CMP = -Wno-write-strings -std=c++11 --exec-charset=UTF-8 -DHSPLINUX -DHSPDEBUG -DHSP_COM_UNSUPPORTED $(CFLAGS_ENV)
PKG_CONFIG = pkg-config

OBJS = \
	src/hsp3/dpmread.do \
	src/hsp3/filepack.do \
	src/hsp3/hsp3crypt.do \
	src/hsp3/hsp3utfcnv.do \
	src/hsp3dish/geometry.do \
	src/hsp3/hsp3.do \
	src/hsp3/hsp3code.do \
	src/hsp3/hsp3debug.do \
	src/hsp3dish/hsp3gr_dish.do \
	src/hsp3/hsp3int.do \
	src/hsp3/hspvar_core.do \
	src/hsp3/hspvar_double.do \
	src/hsp3/hspvar_int.do \
	src/hsp3/hspvar_label.do \
	src/hsp3/hspvar_str.do \
	src/hsp3/hspvar_struct.do \
	src/hsp3dish/hspwnd_dish.do \
	src/hsp3dish/hspwnd_obj.do \
	src/hsp3dish/hspwnd_edit.do \
	src/hsp3dish/random.do \
	src/hsp3/stack.do \
	src/hsp3/strbuf.do \
	src/hsp3/strnote.do \
	src/hsp3dish/essprite.do \
	src/hsp3dish/texmes.do \
	src/hsp3dish/sysreq.do \
	src/hsp3dish/emscripten/hgtex.do \
	src/hsp3dish/emscripten/hgiox.do \
	src/hsp3dish/emscripten/mmman.do \
	src/hsp3dish/emscripten/main.do \
	src/hsp3dish/emscripten/stb_image.do \
	src/hsp3dish/emscripten/fontsystem.do \
	src/hsp3dish/obaq/omkedraw.do \
	src/hsp3dish/obaq/hsp3dw.do \
	src/hsp3dish/obaq/game.do \
	src/obaq/physics/rock.do \
	src/obaq/physics/vessel.do \
	src/hsp3dish/raspbian/hsp3dish.do \
	src/hsp3dish/linux/webtask_linux.do \
	src/hsp3/linux/hsp3ext_sock.do \
	src/hsp3/linux/hsp3ext_linux.do \
	src/hsp3/linux/hsp3extlib_ffi.do \
	src/hsp3/linux/devctrl_io.do \
	src/hsp3/linux/supio_linux.do

OBJS_CMP = \
	src/hspcmp/main.o \
	src/hsp3/strbuf.o \
	src/hsp3/linux/supio_linux.o \
	src/hspcmp/token.o \
	src/hspcmp/ahtmodel.o \
	src/hspcmp/ahtobj.o \
	src/hspcmp/codegen.o \
	src/hspcmp/comutil.o \
	src/hspcmp/errormsg.o \
	src/hspcmp/hsc3.o \
	src/hspcmp/hspcmd.o \
	src/hspcmp/label.o \
	src/hspcmp/localinfo.o \
	src/hspcmp/membuf.o \
	src/hsp3/strnote.o \
	src/hspcmp/hsmanager.o \
	src/hspcmp/tagstack.o

OBJS_CL = \
	src/hsp3/linux/main.o \
	src/hsp3/hsp3.o \
	src/hsp3/hsp3code.o \
	src/hsp3/hsp3debug.o \
	src/hsp3/hsp3int.o \
	src/hsp3/hspvar_core.o \
	src/hsp3/hspvar_double.o \
	src/hsp3/hspvar_int.o \
	src/hsp3/hspvar_label.o \
	src/hsp3/hspvar_str.o \
	src/hsp3/hspvar_struct.o \
	src/hsp3/stack.o \
	src/hsp3/strbuf.o \
	src/hsp3/strnote.o \
	src/hsp3/dpmread.o \
	src/hsp3/filepack.o \
	src/hsp3/hsp3crypt.o \
	src/hsp3/hsp3utfcnv.o \
	src/hsp3/linux/supio_linux.o \
	src/hsp3/linux/hsp3cl.o \
	src/hsp3/linux/hsp3ext_linux.o \
	src/hsp3/linux/hsp3ext_sock.o \
	src/hsp3/linux/devctrl_io.o \
	src/hsp3/linux/hsp3extlib_ffi.o \
	src/hsp3/linux/hsp3gr_linux.o

ifeq ($(ENABLE_GPIOD),1)
GPIOD_TARGET = libhsp3gpio_gpiod.so
GPIOD_INSTALL = $(INSTALL) -m 0755 libhsp3gpio_gpiod.so $(DESTDIR)$(OPENHSPDIR)/
endif
SYSFS_TARGET = libhsp3gpio_sysfs.so
SYSFS_INSTALL = $(INSTALL) -m 0755 libhsp3gpio_sysfs.so $(DESTDIR)$(OPENHSPDIR)/

TARGETS = hsp3dish hsp3cl hspcmp hsed $(GPIOD_TARGET) $(SYSFS_TARGET)
CLEAN_TARGETS = hsp3dish hsp3cl hspcmp hsed libhsp3gpio_gpiod.so libhsp3gpio_sysfs.so
LIBS_DISH = -lm -lstdc++ -lcurl -ldl -lpthread -lffi
LIBS_CL = -lm -lstdc++ -lcurl -ldl -lpthread -lffi
LIBS_GP = \
	libgameplay.a \
	libBulletDynamics.a \
	libBulletCollision.a \
	libLinearMath.a

all: $(TARGETS)

.PHONY: all install uninstall clean

.SUFFIXES: .cpp
hsp3dish: $(OBJS)
	$(CXX) $(CFLAGS_DISH) $(OBJS) $(LDFLAGS) -s -o $@ $(LIBS_DISH)
%.do: %.c
	$(CC) $(CFLAGS_DISH) -c $< -o $*.do
%.do: %.cpp
	$(CXX) $(CFLAGS_DISH) -c $< -o $*.do

hspcmp: $(OBJS_CMP)
	$(CXX) $(CFLAGS_CMP) $(OBJS_CMP) -s -o $@
%.o: %.c
	$(CC) $(CFLAGS_CMP) -c $< -o $*.o
%.o: %.cpp
	$(CXX) $(CFLAGS_CMP) -c $< -o $*.o

hsp3cl: $(OBJS_CL)
	$(CXX) $(CFLAGS_CL) $(OBJS_CL) $(LDFLAGS) -s -o $@ $(LIBS_CL)
%.o: %.c
	$(CC) $(CFLAGS_CL) -c $< -o $*.o
%.o: %.cpp
	$(CXX) $(CFLAGS_CL) -c $< -o $*.o

libhsp3gpio_gpiod.so: src/hsp3/linux/devctrl_gpio_gpiod.cpp
	$(CXX) $(CFLAGS_ENV) -fPIC -shared $(LDFLAGS) -o $@ $< -lgpiod

libhsp3gpio_sysfs.so: src/hsp3/linux/devctrl_gpio_sysfs.cpp
	$(CXX) $(CFLAGS_ENV) -fPIC -shared $(LDFLAGS) -o $@ $<

hsed: src/tools/linux/hsed_gtk2.cpp src/tools/linux/supio.cpp
	$(CXX) -O2 -Wno-write-strings -o hsed src/tools/linux/hsed_gtk2.cpp src/tools/linux/supio.cpp `$(PKG_CONFIG) --cflags --libs gtk+-2.0`

install: $(TARGETS)
	$(INSTALL) -d $(DESTDIR)$(BINDIR)
	$(INSTALL) -d $(DESTDIR)$(OPENHSPDIR)
	$(INSTALL) -d $(DESTDIR)$(APPDIR)
	$(INSTALL) -d $(DESTDIR)$(PIXMAPDIR)
	$(INSTALL) -m 0755 hspcmp hsp3cl hsp3dish hsed $(DESTDIR)$(OPENHSPDIR)/
	$(GPIOD_INSTALL)
	$(SYSFS_INSTALL)
	$(INSTALL) -d $(DESTDIR)$(OPENHSPDIR)/common
	cp -a common/. $(DESTDIR)$(OPENHSPDIR)/common/
	$(INSTALL) -d $(DESTDIR)$(OPENHSPDIR)/hsphelp
	cp -a hsphelp/. $(DESTDIR)$(OPENHSPDIR)/hsphelp/
	$(INSTALL) -m 0644 hsed.desktop $(DESTDIR)$(APPDIR)/
	$(INSTALL) -m 0644 hsed.png $(DESTDIR)$(PIXMAPDIR)/
	printf '%s\n' '#!/bin/sh' 'exec $(OPENHSPDIR)/hspcmp --compath=$(OPENHSPDIR)/common/ --syspath=$(OPENHSPDIR)/ "$$@"' > $(DESTDIR)$(BINDIR)/hspcmp
	printf '%s\n' '#!/bin/sh' 'exec $(OPENHSPDIR)/hsp3cl "$$@"' > $(DESTDIR)$(BINDIR)/hsp3cl
	printf '%s\n' '#!/bin/sh' 'exec $(OPENHSPDIR)/hsp3dish "$$@"' > $(DESTDIR)$(BINDIR)/hsp3dish
	printf '%s\n' '#!/bin/sh' 'exec $(OPENHSPDIR)/hsed "$$@"' > $(DESTDIR)$(BINDIR)/hsed
	chmod 0755 $(DESTDIR)$(BINDIR)/hspcmp $(DESTDIR)$(BINDIR)/hsp3cl $(DESTDIR)$(BINDIR)/hsp3dish $(DESTDIR)$(BINDIR)/hsed

uninstall:
	rm -f $(DESTDIR)$(BINDIR)/hspcmp $(DESTDIR)$(BINDIR)/hsp3cl $(DESTDIR)$(BINDIR)/hsp3dish $(DESTDIR)$(BINDIR)/hsed
	rm -f $(DESTDIR)$(APPDIR)/hsed.desktop
	rm -f $(DESTDIR)$(PIXMAPDIR)/hsed.png
	rm -rf $(DESTDIR)$(OPENHSPDIR)

clean:
	rm -f $(OBJS) $(OBJS_CMP) $(OBJS_CL) $(CLEAN_TARGETS)
