.TH HSED 1 "July 2026" "OpenHSP 3.8 beta1" "User Commands"
.SH NAME
hsed \- edit Hot Soup Processor scripts
.SH SYNOPSIS
.B hsed
.RI [ file.hsp ]
.SH DESCRIPTION
.B hsed
starts the GTK script editor for Hot Soup Processor.
.PP
The Debian package installs this command as a wrapper around the editor in
.IR /usr/lib/openhsp .
.SH SEE ALSO
.BR hspcmp (1),
.BR hsp3dish (1)
