.TH HSP3DISH 1 "July 2026" "OpenHSP 3.8 beta1" "User Commands"
.SH NAME
hsp3dish \- run a Hot Soup Processor HSP3Dish program
.SH SYNOPSIS
.B hsp3dish
.RI [ file.ax ]
.SH DESCRIPTION
.B hsp3dish
runs a compiled Hot Soup Processor AX program with the HSP3Dish runtime.
.PP
The Debian package installs this command as a wrapper around the runtime in
.IR /usr/lib/openhsp .
.SH SEE ALSO
.BR hspcmp (1),
.BR hsp3cl (1)
