.TH HSP3GP 1 "July 2026" "OpenHSP 3.8 beta1" "User Commands"
.SH NAME
hsp3gp \- run a Hot Soup Processor HGIMG4 program
.SH SYNOPSIS
.B hsp3gp
.RI [ file.ax ]
.SH DESCRIPTION
.B hsp3gp
runs a compiled Hot Soup Processor AX program with the HGIMG4 runtime.
.PP
The Debian package installs this command as a wrapper around the runtime in
.IR /usr/lib/openhsp .
.SH SEE ALSO
.BR hspcmp (1),
.BR hsp3dish (1)
