/* Generated by OpenHSP. Do not edit this file directly.
 * g++ -shared -fPIC -g -O2 -o ao_opt.so ao_opt.cpp
 */
#include "chsp.h"

extern "C" {
double vdot(double *v0, double *v1) {
    return v0[0] * v1[0] + v0[1] * v1[1] + v0[2] * v1[2];
}

void vcross(double *c, double *v0, double *v1) {
    c[0] = v0[1] * v1[2] - v0[2] * v1[1];
    c[1] = v0[2] * v1[0] - v0[0] * v1[2];
    c[2] = v0[0] * v1[1] - v0[1] * v1[0];
    return;
}

void vnormalize(double* c)
{
    double len;
    len = sqrt(vdot(c, c));
    c[0] /= len;
    c[1] /= len;
    c[2] /= len;
    return;
}

double vadot(double* v0, int i0, double* v1, int i1) {
    return v0[i0*3+0] * v1[i1*3+0] + v0[i0*3+1] * v1[i1*3+1] + v0[i0*3+2] * v1[i1*3+2];
}

void vacross(double* c, int ci, double* v0, int i0, double* v1, int i1)
{
    c[ci*3+0] = v0[i0*3+1] * v1[i1*3+2] - v0[i0*3+2] * v1[i1*3+1];
    c[ci*3+1] = v0[i0*3+2] * v1[i1*3+0] - v0[i0*3+0] * v1[i1*3+2];
    c[ci*3+2] = v0[i0*3+0] * v1[i1*3+1] - v0[i0*3+1] * v1[i1*3+0];
    return;
}

void vanormalize(double* c, int i)
{
    double len;
    len = sqrt(vadot(c, i, c, i));
    c[i*3+0] /= len;
    c[i*3+1] /= len;
    c[i*3+2] /= len;
    return;
}

void ray_sphere_intersect(double* spheres_center, double* spheres_radius, double* spheres_col, double* isect, double* isect_p, double* isect_n, double* ray_org, double* ray_dir, int no)
{
    double rs[3];
    double b;
    double c;
    double d;
    double t;
	// ddim rs, 3
	rs[0] = ray_org[0] - spheres_center[no*3+0];
	rs[1] = ray_org[1] - spheres_center[no*3+1];
	rs[2] = ray_org[2] - spheres_center[no*3+2];

	b = vdot(rs, ray_dir);
	c = vdot(rs, rs) - spheres_radius[no] * spheres_radius[no];
	d = b * b - c;
	if (d > 0) {
		t = -b - sqrt(d);
//			color 255,0,0 : pos 0,0 : mes "d = " + d + ", " + t
		if ((t > 0) && (t < isect[0])) {
			isect[0] = t;
			isect[1] += 1.0;

			isect[2] = spheres_col[no*3+0];
			isect[3] = spheres_col[no*3+1];
			isect[4] = spheres_col[no*3+2];

			isect_p[0] = ray_org[0] + ray_dir[0] * t;
			isect_p[1] = ray_org[1] + ray_dir[1] * t;
			isect_p[2] = ray_org[2] + ray_dir[2] * t;

			isect_n[0] = isect_p[0] - spheres_center[no*3+0];
			isect_n[1] = isect_p[1] - spheres_center[no*3+1];
			isect_n[2] = isect_p[2] - spheres_center[no*3+2];

			vnormalize(isect_n);
		}
	}
	return;
}

void ray_plane_intersect(double* plane_p, double* plane_n, double* plane_col, double* isect, double* isect_p, double* isect_n, double* ray_org, double* ray_dir)
{
    double rs;
    double d;
    double v;
    double t;
    d = - vdot(plane_p, plane_n);
    v = vdot(ray_dir, plane_n);

    if (fabs(v) < 1.0e-17) {
        return;
    }

    t = - (vdot(ray_org, plane_n) + d) / v;

    if ((t > 0) && (t < isect[0])) {
        isect[0] = t;
        isect[1] += 1.0;

        isect[2] = plane_col[0];
        isect[3] = plane_col[1];
        isect[4] = plane_col[2];

        isect_p[0] = ray_org[0] + ray_dir[0] * t;
        isect_p[1] = ray_org[1] + ray_dir[1] * t;
        isect_p[2] = ray_org[2] + ray_dir[2] * t;

        isect_n[0] = plane_n[0];
        isect_n[1] = plane_n[1];
        isect_n[2] = plane_n[2];

//color 255, 0, 0 : mes " " + isect(2) + "." + isect(3) + "." + isect(4)
    }
    return;
}

}