/* Generated by OpenHSP. Do not edit this file directly.
 * g++ -shared -fPIC -g -O2 -o ao_opt.so ao_opt.cpp
 */
#include "chsp.h"

int rnd(int n) {
    return rand() % n;
}

extern "C" {

double drand() {
    return double(rnd(32768)) / 32768.0;
}


double vdot(double *v0, double *v1) {
    return v0[0] * v1[0] + v0[1] * v1[1] + v0[2] * v1[2];
}

void vcross(double *c, double *v0, double *v1) {
    c[0] = v0[1] * v1[2] - v0[2] * v1[1];
    c[1] = v0[2] * v1[0] - v0[0] * v1[2];
    c[2] = v0[0] * v1[1] - v0[1] * v1[0];
    return;
}

void vnormalize(double* c)
{
    double len;
    len = sqrt(vdot(c, c));
    c[0] /= len;
    c[1] /= len;
    c[2] /= len;
    return;
}

double vadot(double* v0, int i0, double* v1, int i1) {
    return v0[i0*3+0] * v1[i1*3+0] + v0[i0*3+1] * v1[i1*3+1] + v0[i0*3+2] * v1[i1*3+2];
}

void vacross(double* c, int ci, double* v0, int i0, double* v1, int i1)
{
    c[ci*3+0] = v0[i0*3+1] * v1[i1*3+2] - v0[i0*3+2] * v1[i1*3+1];
    c[ci*3+1] = v0[i0*3+2] * v1[i1*3+0] - v0[i0*3+0] * v1[i1*3+2];
    c[ci*3+2] = v0[i0*3+0] * v1[i1*3+1] - v0[i0*3+1] * v1[i1*3+0];
    return;
}

void vanormalize(double* c, int i)
{
    double len;
    len = sqrt(vadot(c, i, c, i));
    c[i*3+0] /= len;
    c[i*3+1] /= len;
    c[i*3+2] /= len;
    return;
}

void ray_sphere_intersect(double* spheres_center, double* spheres_radius, double* spheres_col, double* isect, double* isect_p, double* isect_n, double* ray_org, double* ray_dir, int no)
{
    double rs[3];
    double b;
    double c;
    double d;
    double t;
    // ddim rs, 3
    rs[0] = ray_org[0] - spheres_center[no*3+0];
    rs[1] = ray_org[1] - spheres_center[no*3+1];
    rs[2] = ray_org[2] - spheres_center[no*3+2];

    b = vdot(rs, ray_dir);
    c = vdot(rs, rs) - spheres_radius[no] * spheres_radius[no];
    d = b * b - c;
    if (d > 0) {
        t = -b - sqrt(d);
        if ((t > 0) && (t < isect[0])) {
            isect[0] = t;
            isect[1] += 1.0;

            isect[2] = spheres_col[no*3+0];
            isect[3] = spheres_col[no*3+1];
            isect[4] = spheres_col[no*3+2];

            isect_p[0] = ray_org[0] + ray_dir[0] * t;
            isect_p[1] = ray_org[1] + ray_dir[1] * t;
            isect_p[2] = ray_org[2] + ray_dir[2] * t;

            isect_n[0] = isect_p[0] - spheres_center[no*3+0];
            isect_n[1] = isect_p[1] - spheres_center[no*3+1];
            isect_n[2] = isect_p[2] - spheres_center[no*3+2];

            vnormalize(isect_n);
        }
    }
    return;
}

void ray_plane_intersect(double* plane_p, double* plane_n, double* plane_col, double* isect, double* isect_p, double* isect_n, double* ray_org, double* ray_dir)
{
    double rs;
    double d;
    double v;
    double t;
    d = - vdot(plane_p, plane_n);
    v = vdot(ray_dir, plane_n);

    if (fabs(v) < 1.0e-17) {
        return;
    }

    t = - (vdot(ray_org, plane_n) + d) / v;

    if ((t > 0) && (t < isect[0])) {
        isect[0] = t;
        isect[1] += 1.0;

        isect[2] = plane_col[0];
        isect[3] = plane_col[1];
        isect[4] = plane_col[2];

        isect_p[0] = ray_org[0] + ray_dir[0] * t;
        isect_p[1] = ray_org[1] + ray_dir[1] * t;
        isect_p[2] = ray_org[2] + ray_dir[2] * t;

        isect_n[0] = plane_n[0];
        isect_n[1] = plane_n[1];
        isect_n[2] = plane_n[2];
    }
    return;
}


void ortho_basis(double* basis, double* n)
{
    basis[2*3+0] = n[0];
    basis[2*3+1] = n[1];
    basis[2*3+2] = n[2];
    basis[1*3+0] = 0.0;
    basis[1*3+1] = 0.0;
    basis[1*3+2] = 0.0;

    if ((n[0] < 0.6) && (n[0] > -0.6)) {
        basis[1*3+0] = 1.0;
    } else if ((n[1] < 0.6) && (n[1] > -0.6)) {
        basis[1*3+1] = 1.0;
    } else if ((n[2] < 0.6) && (n[2] > -0.6)) {
        basis[1*3+2] = 1.0;
    } else {
        basis[1*3+0] = 1.0;
    }

    vacross(basis, 0, basis, 1, basis, 2);
    vanormalize(basis, 0);

    vacross(basis, 1, basis, 2, basis, 0);
    vanormalize(basis, 1);

    return;
}

#define eps 0.0001

void ambient_occlusion(
    int nao_samples,
    double* spheres_center, double* spheres_radius, double* spheres_col,
    double* plane_p, double* plane_n, double* plane_col,
    double* col, double* isect, double* isect_p, double* isect_n)
{
    int i; int j;
    double p[3]; double basis[9]; double occlusion; double theta; double phi;
    double x; double y; double z; double rx; double ry; double rz;
    double oray_org[3]; double oray_dir[3]; double occIsect[5]; double occIsect_p[3]; double occIsect_n[3];

    //ddim oray_org, 3
    //ddim oray_dir, 3
    //ddim occIsect, 5
    //ddim occIsect_p, 3
    //ddim occIsect_n, 3
    //ddim p, 3
    //ddim basis, 3*3

    p[0] = isect_p[0] + eps * isect_n[0];
    p[1] = isect_p[1] + eps * isect_n[1];
    p[2] = isect_p[2] + eps * isect_n[2];

    ortho_basis(basis, isect_n);

    occlusion = 0.0;

    for (int cnt = 0; cnt < nao_samples; cnt++) {
        j = cnt;
        for (int cnt = 0; cnt < nao_samples; cnt++) {
            i = cnt;
            theta = sqrt(1.0 * drand());
            phi = 2.0 * M_PI * drand();

            x = cos(phi) * theta;
            y = sin(phi) * theta;
            z = sqrt(1.0 - theta * theta);

            rx = x * basis[0*3+0] + y * basis[1*3+0] + z * basis[2*3+0];
            ry = x * basis[0*3+1] + y * basis[1*3+1] + z * basis[2*3+1];
            rz = x * basis[0*3+2] + y * basis[1*3+2] + z * basis[2*3+2];

            oray_org[0] = p[0];
            oray_org[1] = p[1];
            oray_org[2] = p[2];

            oray_dir[0] = rx;
            oray_dir[1] = ry;
            oray_dir[2] = rz;

            occIsect[0] = 1.0e+17;
            occIsect[1] = 0.0;
            occIsect[2] = 0.0;
            occIsect[3] = 0.0;
            occIsect[4] = 0.0;

            ray_sphere_intersect(spheres_center, spheres_radius, spheres_col, occIsect, occIsect_p, occIsect_n, oray_org, oray_dir, 0);
            ray_sphere_intersect(spheres_center, spheres_radius, spheres_col, occIsect, occIsect_p, occIsect_n, oray_org, oray_dir, 1);
            ray_sphere_intersect(spheres_center, spheres_radius, spheres_col, occIsect, occIsect_p, occIsect_n, oray_org, oray_dir, 2);
            ray_plane_intersect(plane_p, plane_n, plane_col, occIsect, occIsect_p, occIsect_n, oray_org, oray_dir);
            if (occIsect[1] > 0) {
                occlusion += 1.0;
            }
        }
    }

    occlusion = double(nao_samples * nao_samples - occlusion) / double(nao_samples * nao_samples);
    col[0] = occlusion;
    col[1] = occlusion;
    col[2] = occlusion;
    return;
}

}
